### PR TITLE
ROS server publisher, node handle, string vector for pyexotica

### PR DESCRIPTION
**Pull request by christian-rauch**
This PR collects some commits that I used to interface with the `Server`.

- reduce code by using perfect forwarding for ROS publisher instantiation
- make `getNodeHandle` static, since Server is singleton anyway
- add support for `std::vector<std::string>`

### CODE REVIEW

**Comment by wxmerkt** [comment]
Can you please rebase on master? This failed due to #380.

**Comment by christian-rauch** [comment]
CI fails with an unrelated error: `/home/travis/catkin_ws/src/exotica/exotations/task_maps/task_map/include/task_map/CoM.h:38:37: fatal error: task_map/CoMInitializer.h: No such file or directory`
